name: CI

on:
  push:
  pull_request:

jobs:
  regression-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmpfr-dev libgmp-dev libopenblas-dev cmake

      - name: Run regression tests
        run: bash test/run_regression.sh
